# Copyright (C) 2019 Open Source Integrators
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
from odoo import fields, models


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    tms_order_id = fields.Many2one(
        "tms.order",
        "Order",
        index=True,
        copy=False,
        help="TMS Order generated by the sales order item",
    )
