from . import res_config_settings
from . import tms_team
from . import tms_stage
from . import res_partner
from . import tms_crew
from . import tms_order
from . import tms_route
from . import fleet_vehicle
from . import tms_tag
